// <auto-generated />
using ListME.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListMEAPI.Migrations
{
    [DbContext(typeof(ListMEContext))]
    partial class ListMEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ListME.Models.Acesso", b =>
                {
                    b.Property<int>("Id_Acesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Acesso"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Acesso");

                    b.ToTable("Acessos", (string)null);
                });

            modelBuilder.Entity("ListME.Models.Estoque", b =>
                {
                    b.Property<int>("Id_Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Estoque"), 1L, 1);

                    b.Property<string>("Data_Validade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade_Estoque")
                        .HasColumnType("int");

                    b.HasKey("Id_Estoque");

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("ListME.Models.Produtos_ListaDeCompras", b =>
                {
                    b.Property<int>("Id_Produtos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produtos"), 1L, 1);

                    b.Property<string>("Descricao_Produtos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Produtos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<int>("Quantidade_Produtos")
                        .HasColumnType("int");

                    b.HasKey("Id_Produtos");

                    b.ToTable("Produtos da lista de compras", (string)null);
                });

            modelBuilder.Entity("ListME.Models.Residencias", b =>
                {
                    b.Property<int>("Id_Residencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Residencias"), 1L, 1);

                    b.Property<string>("Descricao_Residencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto_Residencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Residencias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Residencias");

                    b.ToTable("Residências", (string)null);
                });

            modelBuilder.Entity("ListME.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"), 1L, 1);

                    b.Property<string>("Data_Nascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto_Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuários", (string)null);
                });

            modelBuilder.Entity("ListME.Models.UsuarioRelacaorResidencia", b =>
                {
                    b.Property<int>("Id_UsuarioRelacaoResidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_UsuarioRelacaoResidencia"), 1L, 1);

                    b.Property<int>("residenciaRelacaoResidenciaId_Residencias")
                        .HasColumnType("int");

                    b.Property<int>("usuarioRelacaoResidenciaId_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_UsuarioRelacaoResidencia");

                    b.HasIndex("residenciaRelacaoResidenciaId_Residencias");

                    b.HasIndex("usuarioRelacaoResidenciaId_Usuario");

                    b.ToTable("RelacaoUsuarioResidencia");
                });

            modelBuilder.Entity("ListME.Models.UsuarioRelacaorResidencia", b =>
                {
                    b.HasOne("ListME.Models.Residencias", "residenciaRelacaoResidencia")
                        .WithMany()
                        .HasForeignKey("residenciaRelacaoResidenciaId_Residencias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListME.Models.Usuario", "usuarioRelacaoResidencia")
                        .WithMany()
                        .HasForeignKey("usuarioRelacaoResidenciaId_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("residenciaRelacaoResidencia");

                    b.Navigation("usuarioRelacaoResidencia");
                });
#pragma warning restore 612, 618
        }
    }
}
